WIDTH = 700;
HEIGHT = 474;
FLOOR = 350;
let bgImage;
let characterLeftOne;
let characterLeftTwo;
let characterLeftJump;
let characterRigthOne;
let characterRigthTwo;
let characterRigthJump;
let sB;
let forkOne;
let knifeOne;
let francesinhaOne;
let francesinhaBossImg;
let sauceImage;
let eatItMusic;
let knifeSound;
let knifeSound2;
let knifeSound3;
let swallowSound;
let beerSound;
let sauceSound;
let bossMusic;
